CREATE TABLE clients (
    id UUID PRIMARY KEY,
    client_id VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    tax_id VARCHAR(14) UNIQUE NOT NULL,
    type VARCHAR(50),
    birth_date DATE,
    marital_status VARCHAR(50),
    birth_place VARCHAR(255),
    mother_name VARCHAR(255),
    gender VARCHAR(20),
    pep BOOLEAN,
    structure VARCHAR(255),
    state VARCHAR(50),
    average_monthly_income NUMERIC(15,2),
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(20),
    identity_number VARCHAR(50),
    identity_issuer VARCHAR(50),
    identity_issuer_state VARCHAR(50),
    zip_code VARCHAR(20),
    address_state VARCHAR(50),
    city VARCHAR(255),
    address VARCHAR(255),
    neighbourhood VARCHAR(255),
    address_number VARCHAR(50),
    bank_branch_number INTEGER,
    bank_account_number INTEGER,
    bank_number VARCHAR(50)
);

CREATE TABLE contracts (
    id UUID PRIMARY KEY,
    client_id UUID NOT NULL,
    contract_type VARCHAR(50),
    value NUMERIC(15,2) NOT NULL,
    interest_rate NUMERIC(5,4) NOT NULL,
    total_installments INTEGER NOT NULL,
    first_due_date DATE,
    grace_period INTEGER,
    finance_iof BOOLEAN,
    account_number VARCHAR(50),
    gross_value NUMERIC(15,2),
    insurance_value NUMERIC(15,2),
    cad_value NUMERIC(15,2),
    iof_value NUMERIC(15,2),
    net_value NUMERIC(15,2),
    annual_interest_rate NUMERIC(5,2),
    cet NUMERIC(5,2),
    cet_annual NUMERIC(5,2),
    release_date DATE,
    initial_due_date DATE,
    final_due_date DATE,
    total_amortization NUMERIC(15,2),
    total_service_fee NUMERIC(15,2),
    total_insurance NUMERIC(15,2),
    total_correction_fee NUMERIC(15,2),
    total_interest NUMERIC(15,2),
    total_installment_value NUMERIC(15,2),
    interest_percentage NUMERIC(5,2),
    tax_percentage NUMERIC(5,2),
    fee_percentage NUMERIC(5,2),
    service_percentage NUMERIC(5,2),
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE installments (
    id SERIAL PRIMARY KEY,
    contract_id UUID NOT NULL,
    installment_number INTEGER NOT NULL,
    due_date DATE NOT NULL,
    principal NUMERIC(15,2),
    correction_value NUMERIC(15,2),
    interest NUMERIC(15,2),
    insurance_value NUMERIC(15,2),
    bank_fee NUMERIC(15,2),
    installment_value NUMERIC(15,2),
    previous_balance NUMERIC(15,2),
    capitalized_interest NUMERIC(15,2),
    current_balance NUMERIC(15,2),
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
);

CREATE TABLE erros_etl (
    id SERIAL PRIMARY KEY,
    etapa VARCHAR(50),
    registro JSONB,
    erro TEXT,
    timestamp TIMESTAMP DEFAULT NOW()
);
